name: Verify a competitor's repo when registering from issue form

on:
  issues:
    types: [labeled]
jobs:
  welcome-msg:
    if: ${{ join(github.event.issue.labels.*.name) == 'registration' }}
    runs-on: ubuntu-latest
    steps:
      - name: Welcome message
        uses: peter-evans/create-or-update-comment@v2.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            #### Welcome to this benchmark!
            In the next few minutes we are doing to do several checks to see if your repository is correctly setup.
            Please note that the automated actions might take a bit of time before showing any feedback.
  verify-competitor:
    needs: [welcome-msg]
    uses: ./.github/workflows/verification.yml
    secrets:
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}