name: Rerun the tests if there was a problem

on:
  issue_comment:
    types: [created]
jobs:
  verify-competitor:
    if: >
      contains(github.event.issue.labels.*.name, 'registration') &&
      contains(github.event.issue.labels.*.name, 'pending') &&
      github.event.issue.user.login == github.event.comment.user.login &&
      contains(github.event.comment.body, 'retry')
    uses: ./.github/workflows/verification.yml
    secrets:
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}